variables:
  APP_NAME: fqacalc
  GIT_STRATEGY: clone
before_script:
  - whoami
  - mkdir -p /srv/shiny-server/$APP_NAME

after_script:
  - echo "Deploy Complete"

deploy:
  stage: deploy
  script:
    - cp -R * /srv/shiny-server/$APP_NAME/
    - cd /srv/shiny-server/$APP_NAME
    - find . -type d \! -name ".*" -user "$(whoami)" \! -perm -g+rwx 2>/dev/null | xargs -I '{}' chmod g+rwx '{}'
    - find . -type d \! -name ".*" -user "$(whoami)" \! -perm -o+rx 2>/dev/null | xargs -I '{}' chmod o+rx '{}'
    - find . -type f \! -name ".*" -user "$(whoami)" \! -perm -g+rw 2>/dev/null | xargs -I '{}' chmod g+rw '{}'
    - find . -type f \! -name ".*" -user "$(whoami)" \! -perm -o+r 2>/dev/null | xargs -I '{}' chmod o+r '{}'
    - find . \! -name ".*" -user "$(whoami)" ! -group shiny 2>/dev/null | xargs -I '{}' chgrp shiny '{}'