variables:
  APP_NAME: fqacalc
  GIT_STRATEGY: clone
before_script:
  - whoami
  - mkdir -p /srv/shiny-server/$APP_NAME

after_script:
  - echo "Deploy Complete"

deploy:
  stage: deploy
  script:
    - cp -R * /srv/shiny-server/$APP_NAME/
    - cd /srv/shiny-server/$APP_NAME
    - find . -type d \! -name ".*" -o \! -name "app_cache" -user "$(whoami)" \! -perm -g+rwx | xargs -I '{}' chmod g+rwx '{}'
    - find . -type d \! -name ".*" -o \! -name "app_cache" -user "$(whoami)" \! -perm -o+rx | xargs -I '{}' chmod o+rx '{}'
    - find . -type f \! -name ".*" -o \! -name "app_cache" -user "$(whoami)" \! -perm -g+rw | xargs -I '{}' chmod g+rw '{}'
    - find . -type f \! -name ".*" -o \! -name "app_cache" -user "$(whoami)" \! -perm -o+r | xargs -I '{}' chmod o+r '{}'
    - find . \! -name ".*" -o \! -name "app_cache" -user "$(whoami)" ! -group shiny | xargs -I '{}' chgrp shiny '{}'