variables:
  APP_NAME: fqacalc
  GIT_STRATEGY: clone
before_script:
  - whoami
  - mkdir -p /srv/shiny-server/$APP_NAME

after_script:
  - echo "Deploy Complete"

deploy:
  stage: deploy
  script:
    - cp -R * /srv/shiny-server/$APP_NAME/
    - cd /srv/shiny-server/$APP_NAME
    - find . ! -readable -prune -o -type d ! -perm -g+rwx -print | xargs -I '{}' chmod g+rwx '{}'
    - find . ! -readable -prune -o -type d ! -perm -o+rx -print | xargs -I '{}' chmod o+rx '{}'
    - find . ! -readable -prune -o -type f ! -perm -g+rw -print | xargs -I '{}' chmod g+rw '{}'
    - find . ! -readable -prune -o -type f ! -perm -o+r -print | xargs -I '{}' chmod o+r '{}'
    - find . ! -readable -prune -o ! -group shiny -print | xargs -I '{}' chgrp shiny '{}'