variables:
  APP_NAME: fqacalc
  GIT_STRATEGY: clone
before_script:
  - whoami
  - mkdir -p /srv/shiny-server/$APP_NAME

after_script:
  - echo "Deploy Complete"

deploy:
  stage: deploy
  script:
    - cp -R * /srv/shiny-server/$APP_NAME/
    - cd /srv/shiny-server/$APP_NAME
    - find . -type d \( ! -name ".*" \) -exec chmod g+rwx {} \; 2>&1 | grep -v "Permission denied";
    - find . -type d \( ! -name ".*" \) -exec chmod a+rx {} \; 2>&1 | grep -v "Permission denied";
    - find . -type f \( ! -name ".*" \) -exec chmod g+rw {} \; 2>&1 | grep -v "Permission denied";
    - find . -type f \( ! -name ".*" \) -exec chmod a+r {} \; 2>&1 | grep -v "Permission denied";
    - find . \( ! -name ".*" \) -exec chgrp -R shiny {} \; 2>&1 | grep -v "Permission denied";