---
output: html_document
---
## Our Mission

The mission of the U.S. Army Corps of Engineers is to deliver vital public and military engineering services; partnering in peace and war to strengthen our nation’s security, energize the economy and reduce risks from disasters.

## About This Application

This is an official public web application developed by the [U.S. Army Engineer Research and Development Center (ERDC)](https://www.erdc.usace.army.mil/), the premier research and development facility of the [U.S. Army Corps of Engineers](https://www.usace.army.mil/). 

This web application was created with funding from the [Aquatic Nuisance Species Research Program](https://www.erdc.usace.army.mil/Missions/Civil-Works/Aquatic-Nuisance-Species-Research-Program/#:~:text=The%20Aquatic%20Nuisance%20Species%20Research,%2C%20infrastructure%2C%20and%20associated%20resources.) (ANSRP) under the [Next Generation Ecological Modeling Program](https://ecomod.erdc.dren.mil/?page_id=447) (Next Gen). ANSRP was was established to address all invasive aquatic animals, as well as, harmful algae species that are problematic to the nation's waterways, infrastructure, and associated resources. Next Gen is an overarching collaboration between ERDC and Texas State University to develop both future modeling efforts and comprehensive data sets. There are many individual projects funded through Next Gen, led by both ERDC and our university partners.

Last Updated: 2024-10-28

To report a mistake or unexpected issue on this webpage, contact - ecomodteam@usace.army.mil

