---
output: html_document
---

## Floristic Quality Assessment

Floristic Quality Assessment (FQA) provides a standardized way to rapidly assess the condition of a vegetated area based on the plant species that are present. FQA works by assigning each plant species a value from 0 to 10. This value is called a Coefficient of Conservatism, or C Value. Values of 0 indicate species that are highly tolerant of human activities and have general environmental needs, while higher values represent higher fidelity to a specific habitat and low tolerance to anthropogenic disturbances. Generally, C values are assigned to either an entire inventory or selected plant species in a region, which may be an entire state (e.g., IN), biome (e.g., Interior Plateau), or specific location (e.g., Middle Rio Grande floodplain) by a group of expert regional botanists. As a result, there are numerous regional FQA databases of flora and their associated C Values covering various geographic areas.

## FQA Databases

In 2022, published, accessible (e.g., Universal FQA Calculator or via Google search with key terms) regional FQA databases were reviewed by the U.S. Army Engineer Research and Development Center’s Environmental Laboratory for use during the planning phase of water resource projects. FQA databases that had clear documentation of their methodology of assigning and testing/validating their C Values were recommended for planning model certification. Then the U.S. Army Corps of Engineers’ Center of Ecosystem Restoration Expertise certified recommended regional FQA databases for USACE planning purposes. Certified regional FQA databases have been compiled and made available for rapid and consistent calculation of FQA metrics within this web application.

Note that *some* of the certified regional FQA databases have been altered slightly from their initial lists to reduce redundancies, indicate which species names are synonyms, or otherwise clarify the data. For a full description of data alterations, see Herman et al., 2023 (in review).

Common floristic quality metrics include Mean C (the mean of C Values for all species present in an inventory or along a transect) and the Floristic Quality Index (FQI, the Mean C multiplied by the square root of the total number of species).

Take a look at what regional FQA database might be applicable in your area:

