---
output: html_document
---

### **Braun-Blanquet**

Braun-Blanquet, Josias. "Plant sociology. The study of plant communities." Plant sociology. The study of plant communities. First ed. (1932).

| Braun-Blanquet Classes | \% Cover Range | Midpoint |
|------------------------|----------------|----------|
| \+                     | \<1%           | 0.1      |
| 1                      | \<5%           | 2.5      |
| 2                      | 5-25%          | 15       |
| 3                      | 25-50%         | 37.5     |
| 4                      | 50-75%         | 62.5     |
| 4                      | 75-100%        | 87.5     |


### **Carolina Veg Survey**

Lee, Michael T., Robert K. Peet, Steven D. Roberts, and Thomas R. Wentworth. "CVS-EEP protocol for recording vegetation." Carolina Vegetation Survey. Retrieved August 17 (2006): 2008.

| Carolina Veg Survey Classes | \% Cover Range | Midpoint |
|-----------------------------|----------------|----------|
| 1                           | \<0.1          | 0.1      |
| 2                           | 0-1%           | 0.5      |
| 3                           | 1-2%           | 1.5      |
| 4                           | 2-5%           | 3.5      |
| 5                           | 5-10%          | 7.5      |
| 6                           | 10-25%         | 17.5     |
| 7                           | 25-50%         | 37.5     |
| 8                           | 50-75%         | 62.5     |
| 9                           | 75-95%         | 85       |
| 10                          | 95-100%        | 97.5     |


### **Daubenmire Classes**

R. F. Daubenmire. "A canopy-cover method of vegetational analysis". Northwest Science 33:43–46. (1959)

| Daubenmire Classes | \% Cover Range | Midpoint |
|--------------------|----------------|----------|
| 1                  | 0-5%           | 2.5      |
| 2                  | 5-25%          | 15       |
| 3                  | 25-50%         | 37.5     |
| 4                  | 50-75%         | 62.5     |
| 5                  | 75-95%         | 85       |
| 6                  | 95-100%        | 97.5     |


### **USFS Ecodata Classes**

Barber, Jim, and Dave Vanderzanden. "The Region 1 existing vegetation map products (VMap) release 9.1." USDA Forest Service, Region 1 (2009): 200.

| USFS Ecodata Classes | \% Cover Range | Midpoint |
|----------------------|----------------|----------|
| 1                    | \<1%           | 0.5      |
| 3                    | 1.1-5%         | 3        |
| 10                   | 5.1-15%        | 10       |
| 20                   | 15.1-25%       | 20       |
| 30                   | 25.1-35%       | 30       |
| 40                   | 35.1-45%       | 40       |
| 50                   | 45.1-55%       | 50       |
| 60                   | 55.1-65%       | 60       |
| 70                   | 65.1-75%       | 70       |
| 80                   | 75.1-85%       | 80       |
| 90                   | 85.1-95%       | 90       |
| 98                   | 95.1-100%      | 98       |
